### ISSUE TITLE
Sending Maya is not working

### ISSUE THREAD

**Issue by frozen4sh** [artbycrunk/vscode-maya#40]
**Describe the bug**

commandPort -name "localhost:7001" -sourceType "mel" -echoOutput;
 # ----------------------------------------# ----------------------------------------
# Exception happened during processing of request from('127.0.0.1', 56580)
# Traceback (most recent call last):
# #   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
# #   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
# #   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
# #   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\socketserver.py", line 720, in __init__
    self.handle()
# #   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\site-packages\maya\app\general\CommandPort.py", line 137, in handle
    self.wfile.write(self.server.commandMessageQueue.get() + self.resp_term)
# #   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
# TypeError: a bytes-like object is required, not 'str'

**To Reproduce**
1. Installed MayaCode extension
2. Click on 'Send Python code to Maya'
3. See error

**Expected behavior**

**Screenshots**
![image](https://github.com/artbycrunk/vscode-maya/assets/43192428/d451af4c-739d-4c1c-91e6-9e9c47423181)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version 10.0.22621 Build 22621

**Smartphone (please complete the following information):**

**Additional context**

**Comment by leohuliuqing** [comment]
i have the same issue

**Comment by ronBublitz** [comment]
same issue still.

**Comment by RalfReddings** [comment]
I am having the same issue as well Maya 2024.1 on Windows 11
Any word from the developer on this?

**Comment by SaravananN313** [comment]
I am facing the same issue as well in Maya 2024.
OS : Windows 10
![error](https://github.com/user-attachments/assets/3fb29d7e-1e43-4f26-897f-ae7852934eae)

**Comment by molly-mocus** [comment]
i have same issue, maya 2022

**Comment by Mamilou** [comment]
Same here, Maya 2022

**Comment by AndershowRig** [comment]
Try using this instead = commandPort -name "localhost:7001" -sourceType "mel"
The solution for me was to remove the -echoOutput;

**Comment by luoxiaohei31** [comment]
I too, can fix it somebody?

**Comment by luoxiaohei31** [comment]
> I too, can fix it somebody?

I know that, reload Maya,  [ use commandPort -name "localhost:7001" -sourceType "mel ], don`t wirte "-echoOutput", thanks bro above.
重启Maya，把[commandPort -name "localhost:7001" -sourceType "mel" -echoOutput] 去掉-echoOutput再运行就行

**Comment by lexikong** [comment]
> Try using this instead = commandPort -name "localhost:7001" -sourceType "mel" The solution for me was to remove the -echoOutput;

removing -echoOutput works for me, thank you!!
