### ISSUE TITLE
issue importing the maya script editor 

### ISSUE THREAD

**Issue by Nabouria** [artbycrunk/vscode-maya#43]
I was trying to us the MEL command 
commandPort -name "localhost:7001" -sourceType "mel" -echoOutput;
.IT seems to work except when I try to use the send to maya in visual studio it gives me this error message. I am still new to this stuff so I'm not sure if its something I did

# ----------------------------------------
# Exception occurred during processing of request from ('127.0.0.1', 51457)
# Traceback (most recent call last):
# #   File "C:\Program Files\Autodesk\Maya2025\Python\Lib\socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
# #   File "C:\Program Files\Autodesk\Maya2025\Python\Lib\socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
# #   File "C:\Program Files\Autodesk\Maya2025\Python\Lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
# #   File "C:\Program Files\Autodesk\Maya2025\Python\Lib\socketserver.py", line 755, in __init__
    self.handle()
# #   File "C:\Program Files\Autodesk\Maya2025\Python\Lib\site-packages\maya\app\general\CommandPort.py", line 134, in handle
    self.wfile.write(self.server.commandMessageQueue.get() + self.resp_term)
# #   File "C:\Program Files\Autodesk\Maya2025\Python\Lib\socketserver.py", line 834, in write
    self._sock.sendall(b)
# TypeError: a bytes-like object is required, not 'str'
# ----------------------------------------

**Comment by Quincy186** [comment]
I have the same problem,  MayaCode also uses version 1.5.0,
